[project]
name = "Logs4Me_Paul_Muabdib"
version = "0.0.1"
authors = [
  { name="Paul Muabdib", email="paul.muabdib.usul@gmail.com" },
]
description = "Simple log system that saves in different files according to the level (TRACE, INFO, WARNNING, ERROR and CRITICAL). "
readme = "README.md"
license = { file="LICENSE" }
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/PMuabdib/Logs4Me"
"Bug Tracker" = "https://github.com/PMuabdib/Logs4Me/issues"